# Site settings
title: Jimmy O'Donnell
description: 'Evolution • Ecology • Numbers • Computers'
url: 'http://jimmyodonnell.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: "Jimmy O'Donnell"
  email: jodonnellbio@gmail.com
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  # github_username:  joshgerdes
  # linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

# COLORS
# original
##  e25440: reddish (links/button borders)
##  b9301c: reddish darker (hover)
## fae3df: pink (selection highlight)

# new
## 4600A0: purple (favicon)
## 3ECBCD: light turqoise ()
## 46C7C7: jellyfish ()
## 48CCCD: medium turqoise ()
## 00cccc: some other turqoise (links)
## 009999: darker version of 00cccc (hover)
## CCF4F4: light turquoise (selection highlighting)
## #e5f9f9: light turquoise alternate
# css/main.css : changes border color of tags
# css/uno.css :
